[0m17:18:30.562951 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a3b0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1048cd760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1084f8c70>]}


============================== 17:18:30.566017 | aef73470-eb71-4628-ac19-c541d029d3b1 ==============================
[0m17:18:30.566017 [info ] [MainThread]: Running with dbt=1.7.11
[0m17:18:30.566441 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/milesleung/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:18:30.566897 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/milesleung/.dbt')}
[0m17:18:30.567154 [info ] [MainThread]: Creating dbt configuration folder at 
[0m17:19:15.520086 [error] [MainThread]: Encountered an error:

[0m17:19:15.542068 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 322, in run
    project_name = self.get_valid_project_name()
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 276, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:19:15.574120 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 45.01596, "process_user_time": 1.296297, "process_kernel_time": 0.117144, "process_mem_max_rss": "95879168", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:19:15.575106 [debug] [MainThread]: Command `dbt init` failed at 17:19:15.574905 after 45.02 seconds
[0m17:19:15.575684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a3b0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1084f8a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10852f0a0>]}
[0m17:19:15.576224 [debug] [MainThread]: Flushing usage events
[0m17:22:45.262410 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054d7280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103129760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ba5c40>]}


============================== 17:22:45.265716 | 311456e9-9024-48d7-99ed-c847ec348956 ==============================
[0m17:22:45.265716 [info ] [MainThread]: Running with dbt=1.7.11
[0m17:22:45.266144 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/milesleung/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:24:16.858256 [error] [MainThread]: Encountered an error:

[0m17:24:16.874592 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 322, in run
    project_name = self.get_valid_project_name()
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 276, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:24:16.875971 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 91.63025, "process_user_time": 1.282752, "process_kernel_time": 0.114162, "process_mem_max_rss": "93847552", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:24:16.876504 [debug] [MainThread]: Command `dbt init` failed at 17:24:16.876384 after 91.63 seconds
[0m17:24:16.876828 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054d7280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ba5970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107be50a0>]}
[0m17:24:16.877144 [debug] [MainThread]: Flushing usage events
[0m17:25:30.884704 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104f33460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102dc5760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1069f0ca0>]}


============================== 17:25:30.887770 | 1c6d4972-ac28-4fa0-8b32-92e5fa4d5dac ==============================
[0m17:25:30.887770 [info ] [MainThread]: Running with dbt=1.7.11
[0m17:25:30.888197 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/milesleung/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:25:47.366370 [debug] [MainThread]: Starter project path: /Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/include/starter_project
[0m17:25:47.382944 [info ] [MainThread]: 
Your new dbt project "custom_postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:25:47.383629 [info ] [MainThread]: Setting up your profile.
[0m17:34:07.555626 [error] [MainThread]: Encountered an error:

[0m17:34:07.632763 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 344, in run
    self.setup_profile(profile_name)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 165, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/task/init.py", line 131, in generate_target_from_input
    target[key] = click.prompt(
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:34:07.636414 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 516.76294, "process_user_time": 1.33638, "process_kernel_time": 0.141054, "process_mem_max_rss": "96567296", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:34:07.638490 [debug] [MainThread]: Command `dbt init` failed at 17:34:07.637793 after 516.76 seconds
[0m17:34:07.639736 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104f33460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d120d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d121c0>]}
[0m17:34:07.641073 [debug] [MainThread]: Flushing usage events
[0m17:36:50.937606 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d4b0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104bdd760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108808c70>]}


============================== 17:36:50.940813 | cf888840-b505-4b9d-959f-348dd2003af9 ==============================
[0m17:36:50.940813 [info ] [MainThread]: Running with dbt=1.7.11
[0m17:36:50.941244 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/milesleung/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:37:21.466926 [debug] [MainThread]: Starter project path: /Users/milesleung/Desktop/pDev/data-engineering/elt/env/lib/python3.9/site-packages/dbt/include/starter_project
[0m17:37:21.484038 [info ] [MainThread]: 
Your new dbt project "custom_postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:37:21.484816 [info ] [MainThread]: Setting up your profile.
[0m17:38:18.163805 [info ] [MainThread]: Profile custom_postgres written to /Users/milesleung/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:38:18.169212 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 87.24563, "process_user_time": 1.311613, "process_kernel_time": 0.134826, "process_mem_max_rss": "96534528", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:38:18.170473 [debug] [MainThread]: Command `dbt init` succeeded at 17:38:18.170186 after 87.25 seconds
[0m17:38:18.171550 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d4b0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c5b3a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104bdd760>]}
[0m17:38:18.172714 [debug] [MainThread]: Flushing usage events
